### PR TITLE
Feature/dark mode

### PR DESCRIPTION
**Pull request by BryanKAdams**

### CODE REVIEW

**Comment by littleonetwo** [comment]
looks good

**Comment by BryanKAdams** [comment]
Looks a lot better, good job.

**Review by littleonetwo — APPROVED** [review]

**Comment by daltonwalkerdw** [comment]
Looks good! Nice and clean!

**Review by daltonwalkerdw — APPROVED** [review]
Looks good, nice and clean!

**Review by mikeyjwilliams — APPROVED** [review]
the dark mode looks good in the unsigned and logged in view

**Pull request merged**
