### PR TITLE
Feature/footer

### PR DESCRIPTION
**Pull request by Chase-42**
Fixed issue with footer floating a little bit off the bottom of the page and links not staying within the footer when in tablet/phone view.

### CODE REVIEW

**Comment by littleonetwo** [comment]
Footer wasnt working on my machine.. maybe due to resolution

**Review by mikeyjwilliams — COMMENTED** [review]
in the Footer.jsx component would we be able to make it a footer element?
by changing it from a div element into a footer element for more semantic markup and giving it a landmark?
if you disagree of the change, just state your thoughts on this. thank you

**Comment by Chase-42** [comment]
> in the Footer.jsx component would we be able to make it a footer element?
> by changing it from a div element into a footer element for more semantic markup and giving it a landmark?
> if you disagree of the change, just state your thoughts on this. thank you

No, that makes perfect sense!

**Review by mikeyjwilliams — APPROVED** [review]
testing on my machine worked well, thank you for the semantic change.

**Comment by littleonetwo** [comment]
it's better in 2k view but it's still not fixed in dashboard

**Comment by Chase-42** [comment]
> it's better in 2k view but it's still not fixed in dashboard

I'll continue to fiddle and try and find a way to fix this but I've applied every trick I can find and it's a little hard to debug since I am not seeing this issue on my screens.

**Comment by littleonetwo** [comment]
No I understand.. here's how I fixed it..

in the footer.scss
`.footer {
	background-color: $erudite-purple;
	display: flex;
	flex-direction: column;
	justify-content: flex-end;
	padding: 15px;
	height: 338px;

	@media (max-width: '750px') {
		height: 385px;
	}
	.links-container {
		display: flex;
		justify-content: space-around;
		margin: 0 auto;
		width: 80%;
		max-width: 1400px;
		@media (max-width: '750px') {
			flex-direction: column;
			text-align: center;
			padding: 0;
		}

		li {
			margin-top: 5rem;
			@media (max-width: '750px') {
				margin: 1.4rem 0rem;
				padding: 0.25rem;
			}
			@media #{$mobile} {
				margin-top: auto;
			}
			a {
				color: $snow-white;
				font-size: 2.6rem;
				@media #{$mobile} {
					font-size: 3rem;
				}
			}
		}
	}`

I made a new file called pagecontainer.scss
`html, body, #root {
  height:100%;
  margin:0;
}



.page-container{
  min-height: 100%;
  margin-bottom: -339px;

}
`
Then in the dashboard.jsx make a new div called page-container between the div Dashboard-container and Nav.. close the new div before footer.. I think that should fix it

**Comment by Chase-42** [comment]
> No I understand.. here's how I fixed it..
> 
> in the footer.scss
> `.footer {
> background-color: $erudite-purple;
> display: flex;
> flex-direction: column;
> justify-content: flex-end;
> padding: 15px;
> height: 338px;
> 
> ```
> @media (max-width: '750px') {
> 	height: 385px;
> }
> .links-container {
> 	display: flex;
> 	justify-content: space-around;
> 	margin: 0 auto;
> 	width: 80%;
> 	max-width: 1400px;
> 	@media (max-width: '750px') {
> 		flex-direction: column;
> 		text-align: center;
> 		padding: 0;
> 	}
> 
> 	li {
> 		margin-top: 5rem;
> 		@media (max-width: '750px') {
> 			margin: 1.4rem 0rem;
> 			padding: 0.25rem;
> 		}
> 		@media #{$mobile} {
> 			margin-top: auto;
> 		}
> 		a {
> 			color: $snow-white;
> 			font-size: 2.6rem;
> 			@media #{$mobile} {
> 				font-size: 3rem;
> 			}
> 		}
> 	}
> }`
> ```
> 
> I made a new file called pagecontainer.scss
> `html, body, #root {
> height:100%;
> margin:0;
> }
> 
> .page-container{
> min-height: 100%;
> margin-bottom: -339px;
> 
> }
> `
> Then in the dashboard.jsx make a new div called page-container between the div Dashboard-container and Nav.. close the new div before footer.. I think that should fix it

**Comment by Chase-42** [comment]
> > No I understand.. here's how I fixed it..
> > in the footer.scss
> > `.footer {
> > background-color: $erudite-purple;
> > display: flex;
> > flex-direction: column;
> > justify-content: flex-end;
> > padding: 15px;
> > height: 338px;
> > ```
> > @media (max-width: '750px') {
> > 	height: 385px;
> > }
> > .links-container {
> > 	display: flex;
> > 	justify-content: space-around;
> > 	margin: 0 auto;
> > 	width: 80%;
> > 	max-width: 1400px;
> > 	@media (max-width: '750px') {
> > 		flex-direction: column;
> > 		text-align: center;
> > 		padding: 0;
> > 	}
> > 
> > 	li {
> > 		margin-top: 5rem;
> > 		@media (max-width: '750px') {
> > 			margin: 1.4rem 0rem;
> > 			padding: 0.25rem;
> > 		}
> > 		@media #{$mobile} {
> > 			margin-top: auto;
> > 		}
> > 		a {
> > 			color: $snow-white;
> > 			font-size: 2.6rem;
> > 			@media #{$mobile} {
> > 				font-size: 3rem;
> > 			}
> > 		}
> > 	}
> > }`
> > ```
> > 
> > 
> > I made a new file called pagecontainer.scss
> > `html, body, #root {
> > height:100%;
> > margin:0;
> > }
> > .page-container{
> > min-height: 100%;
> > margin-bottom: -339px;
> > }
> > `
> > Then in the dashboard.jsx make a new div called page-container between the div Dashboard-container and Nav.. close the new div before footer.. I think that should fix it
 

Okay, awesome - I will add that to the code. Thanks for the help!

**Comment by littleonetwo** [comment]
I forgot to add.. dont forget to add the new file to styles/base.scss..

`@import '../components/Layout/PageContainer.scss';`

**Comment by Chase-42** [comment]
> I forgot to add.. dont forget to add the new file to styles/base.scss..
> 
> `@import '../components/Layout/PageContainer.scss';`

Ah... yes, thank you for the reminder!

**Pull request closed without merging**
