### PR TITLE
Feature/refactor

### PR DESCRIPTION
**Pull request by littleonetwo**
various things to make the site more modern and more design around being a single page app in React

### CODE REVIEW

**Review by daltonwalkerdw — APPROVED** [review]

**Review by littleonetwo — COMMENTED** [review]
Works!

**Review by Chase-42 — APPROVED** [review]
Looks good to me

**Review by mikeyjwilliams — APPROVED** [review]
work is good, nice updates

**Review by Surfsol — APPROVED** [review]
Tested and working

**Pull request merged**
